version: "3.8"

services:
  github-mcp:
    image: ghcr.io/github/github-mcp-server:latest
    container_name: github-mcp-server
    restart: unless-stopped
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_TOKEN}
      - GITHUB_TOOLSETS=all
    stdin_open: true # Keep STDIN open
    tty: true # Allocate a pseudo-TTY
    command: ["stdio"]
